name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build with Next.js
        run: |
          echo "Building Next.js application..."
          npm run build:github

          # Manual static export fallback (required due to config conflicts)
          if [ ! -d "./out" ]; then
            echo "Creating manual static export..."
            mkdir -p out
            
            # Copy static assets
            if [ -d ".next/static" ]; then
              mkdir -p out/_next/static
              cp -r .next/static/* out/_next/static/
            fi
            
            # Copy HTML files
            find .next -name "*.html" -type f | while read -r file; do
              basename_file=$(basename "$file")
              cp "$file" "out/$basename_file"
            done
            
            # Copy public files
            if [ -d "public" ]; then
              cp -r public/* out/ 2>/dev/null || true
            fi
            
            echo "Manual static export completed"
          fi
        env:
          NEXT_PUBLIC_N8N_BASE_URL: ${{ secrets.NEXT_PUBLIC_N8N_BASE_URL }}
          NEXT_PUBLIC_N8N_SCHEDULE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_N8N_SCHEDULE_ENDPOINT }}
          NEXT_PUBLIC_N8N_TASKS_ENDPOINT: ${{ secrets.NEXT_PUBLIC_N8N_TASKS_ENDPOINT }}
          NEXT_PUBLIC_APP_SECRET: ${{ secrets.NEXT_PUBLIC_APP_SECRET }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
